language: node_js
node_js:
- '10'
- '12'
jobs:
  include:
    - stage: e2e
      script: bash ./run_e2e_tests.sh $API_KEY $TEST_CLIENT_ID $TEST_URL_LOCAL
addons:
  apt:
    packages:
      - libgconf-2-4
